from enum import Enum

BLUE = (0, 0, 255)
LIGHT_GREY = (180, 180, 180)

THING_SIZE = 4
THING_COLOR = BLUE

NUMBER_OF_THINGS = 3000
NUMBER_OF_GENES_IN_GENOME = 15
NUMBER_OF_NURONS = 4
WORLD_SIZE = 128
GRID_SIZE = 4
DISPLAY_SIZE = WORLD_SIZE * GRID_SIZE

BACKGROUND_COLOR = LIGHT_GREY
FPS = 10


class GeneCellType(Enum):
    SENSOR = 1
    NURON = 2
    ACTUATOR = 3
